### ISSUE TITLE
CVSS 4.0 calculator does not calculate a score of 0

### ISSUE THREAD

**Issue by AZoumis** [Rootshell-Security/cvss-calculator#12]
# Problem description
A CVSS 4.0 vector with an expected result of 0 returns a non-zero score instead

# Example
The vector CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N should have a score of 0, but the 6.9 is returned.

**Comment by liamh101** [comment]
Replicated the issue. Thanks for raising.

**Comment by liamh101** [comment]
Fixed in release 1.4.4.
